### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by 0323pin**
Second attempt at updating all crate dependencies.
Resolves https://github.com/sstadick/hck/issues/83

cargo audit is happy now,
```
~> cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 617 security advisories (from /home/pin/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (118 crate dependencies)
```

Let's hope the CI is also happy.

### CODE REVIEW

**Comment by sstadick** [comment]
Awesome!  Thanks for starting on this @0323pin. 

Two things:

- to get CI to pass you'll need to update the thirdparty.yaml

```
cargo bundle-licenses --format yaml --output new.yaml --previous THIRDPARTY.yml
mv new.yaml THIRDPARTY.yml
```

- To play it safe I think I'd prefer to update to 0.10.0

If I get some time later today I'll try to make a PR into this PR with those changes 👍

**Comment by 0323pin** [comment]
@sstadick Thanks, I can try to fix this. Don't know if I have time tonight though.

**Comment by 0323pin** [comment]
@sstadick All checks have passed 🚀

**Comment by sstadick** [comment]
New version should be live in crates.io now! v0.10.0

Thanks for pushing this through!

**Comment by 0323pin** [comment]
Thank you!

**Pull request merged**
