### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by 0323pin**
@sstadick `clippy` isn't happy again and outputs two warnings but, let's try ...

### CODE REVIEW

**Comment by 0323pin** [comment]
🚀  All tests passed.

So `clippy` using rust-1.76 in the CI is happy 🥳 

But, locally with rust-1.80.1 I get the following:

```
    Checking hck v0.10.2 (/home/pin/Downloads/hck)
warning: transmute used without annotations
   --> src/lib/core.rs:448:44
    |
448 |             shuffler = unsafe { core::mem::transmute(s) };
    |                                            ^^^^^^^^^ help: consider adding missing annotations: `transmute::<std::vec::Vec<std::vec::Vec<&[u8]>>, std::vec::Vec<std::vec::Vec<&[u8]>>>`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_transmute_annotations
    = note: `#[warn(clippy::missing_transmute_annotations)]` on by default

warning: transmute used without annotations
   --> src/lib/core.rs:524:48
    |
524 |                 shuffler = unsafe { core::mem::transmute(s) };
    |                                                ^^^^^^^^^ help: consider adding missing annotations: `transmute::<std::vec::Vec<std::vec::Vec<&[u8]>>, std::vec::Vec<std::vec::Vec<&[u8]>>>`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_transmute_annotations

warning: `hck` (lib) generated 2 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 01s
```

Might be good to fix these. Unfortunately, I'm not a programmer.
Away for the weekend but, can reply from mobile.

**Comment by 0323pin** [comment]
```
warning: can be more succinctly written as a byte str
  --> src/lib/core.rs:29:30
   |
29 | const DEFAULT_DELIM: &[u8] = &[b'\t'];
   |                              ^^^^^^^^ help: try: `b"\t"`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#byte_char_slices
   = note: `#[warn(clippy::byte_char_slices)]` on by default

warning: transmute used without annotations
   --> src/lib/core.rs:448:44
    |
448 |             shuffler = unsafe { core::mem::transmute(s) };
    |                                            ^^^^^^^^^ help: consider adding missing annotations: `transmute::<std::vec::Vec<std::vec::Vec<&[u8]>>, std::vec::Vec<std::vec::Vec<&[u8]>>>`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_transmute_annotations
    = note: `#[warn(clippy::missing_transmute_annotations)]` on by default

warning: transmute used without annotations
   --> src/lib/core.rs:524:48
    |
524 |                 shuffler = unsafe { core::mem::transmute(s) };
    |                                                ^^^^^^^^^ help: consider adding missing annotations: `transmute::<std::vec::Vec<std::vec::Vec<&[u8]>>, std::vec::Vec<std::vec::Vec<&[u8]>>>`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_transmute_annotations

warning: `hck` (lib) generated 3 warnings
```

**Comment by sstadick** [comment]
Thanks for the persistence on this! I'll give it a shot sometime in the next week or so and see if I can fix it up. 

I'm back in a spot where I'm using this tool myself again, which will hopefully inspire speedier turnarounds!

**Comment by 0323pin** [comment]
Cheers!

It does build locally with Rust-1.82

**Comment by sstadick** [comment]
@0323pin - fixed clippy at least. Will need to re-remind myself how to run the thirdparty yaml bit and ran out of time this morning, but will pick it back up: https://github.com/sstadick/hck/pull/91

**Comment by sstadick** [comment]
Nevermind, I think I fixed it! If that PR looks reasonable to you I'll merge it and make a release. It updates to 1.82, so unless that should in turn bump more versions, I think it should be good to go?

**Comment by 0323pin** [comment]
#91 looks good, thanks for fixing `clippy`

> Will need to re-remind myself how to run the thirdparty yaml bit

I did that :)
```
~> cargo bundle-licenses --format yaml --output new.yaml --previous THIRDPARTY.yml
~> mv new.yaml THIRDPARTY.yml
```

> It updates to 1.82

I was hoping to stay on 1.81 because, that's the latest version in tree on NetBSD. But, I have 1.82 locally so, for personal use that's fine. I won't be able to merge a package for a new release before early January as, we are approaching branching stable and it's too late to update Rust.

**Comment by sstadick** [comment]
See https://github.com/sstadick/hck/pull/91

**Comment by sstadick** [comment]
And the release part of CI failed. I'll check that out tomorrow. It's at least released in crates.io and tagged in git.

**Comment by 0323pin** [comment]
Thanks for rolling back to 1.81 and for fixing the ` clippy` warnings. I'll try to update the package soon but, might take a day or so.

**Pull request closed without merging**
